version: "3.9"

services:
  ingest:
    build: .
    env_file:
      - .env
    command: python ingestion/ingest_trips.py --file ingestion/data/trips.csv

  api:
    build: .
    env_file:
      - .env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  dbt:
    build: .
    env_file:
      - .env
    command: dbt run --project-dir dbt_project --profiles-dir dbt_project

