name: 'data_engineering_challenge'
version: '1.0'
config-version: 2

profile: 'data_challenge_profile'
model-paths: ["models"]

models:
  data_engineering_challenge:
    staging:
      +materialized: view
    marts:
      +materialized: table